### ISSUE TITLE
How to wrap vue2-editor in a reusable component with v-model?

### ISSUE THREAD

**Issue by andrewhl** [davidroyer/vue2-editor#129]
I want to create a reusable Editor component that wraps the vue2-editor. I want to be able to do this:

```javascript
<Editor v-model="content" />
``` 

And have that render the `<vue-editor>` component.

In order to achieve this, I need to follow the requires for using `v-model`, [explained here](https://vuejs.org/v2/guide/components.html#Using-v-model-on-Components). I need to be able to define a `prop` of `value` on my `Editor` component, and listen to some kind of change event on `vue-editor`, and `$emit('input', $event.target.value)`, or something along those lines. However, the only event listener provided by the component is `imageAdded`. How can I create a reusable component wrapper for `vue-editor`?

**Comment by davidroyer** [comment]
Hey @andrewhl,

Since Vue2Editor is already an input element and using `v-model`, I don't believe using `v-model` in the wrapper component such as: `<Editor v-model="content" />` is way to approach it.

That's like having an input nested inside another input.

However, you can use `.sync` instead. Here's an example I made illustrating how to accomplish what I believe you are wanting.

[CodeSandbox Demo](https://codesandbox.io/s/j34wqvvw75)

I'm going to close this out but you can reopen it if needed. Best of luck!

**Comment by andrewhl** [comment]
@davidroyer Love it! And I learned something. I didn't know about .sync. Very cool. Thanks
