### ISSUE TITLE
Need ImageDeleted Event

### ISSUE THREAD

**Issue by cys02688** [davidroyer/vue2-editor#139]
We need a new event ---- 'ImageDeleted'.
I need to "DELETE" the image url by axios when the picture was deleted.

**Comment by davidroyer** [comment]
A new event has been added as of 2.10.0. This new event is `imageRemoved`.

I plan to add more information to the Docs soon.
However, I have created an [example](https://codesandbox.io/s/vue2editor-imagehandlers-49twn) on CodeSandbox.

Closes #175

**Comment by rajesh-h** [comment]
I was trying this solution, but I am getting error "document is not defined"  I am sure this is popping up because of quill.  How do i import Quill properly? I have been trying this from last two days.

Your sandbox code doesn't have any plugin import for Quill not sure why it is not throwing error.  I am trying to work this on Nuxt

@davidroyer any help is appreciated. It's been two days I am struggling with this.
