### ISSUE TITLE
getting data values 

### ISSUE THREAD

**Issue by murilolivorato** [davidroyer/vue2-editor#14]
If I try to do this - 
```
<vue-editor   :editor-content="textvalue"   @editor-updated="textvalue" :use-save-button="false"  ></vue-editor>
```
the mouse allays goes to beginning of the text area , and if I type 
abcdf

It will type 
fdcba

the only way to solve that , is to make in differents data , one data to recive , and one data to send the new value . like this - 

```
<vue-editor   :editor-content="textvalue1"   @editor-updated="textvalue2" :use-save-button="false"  ></vue-editor>
```

does have any how to solve that ?
Thanks

**Comment by davidroyer** [comment]
Hi, 

` @editor-updated ` is an event. Instead of setting it equal to textvalue2, set it equal to a method you declare in your code.  Depending on how you are needing to use the editor, its possible you don't even need to use the `@editor-updated` event. If that is the case then all you would need is:
`<vue-editor   :editor-content="textvalue" :use-save-button="false"></vue-editor>`


I'm going to close this issue but if you are still unable to get the desired results, feel free to explain in more detail the functionality you are hoping to achieve.
