### ISSUE TITLE
Error when adding two editors in a view

### ISSUE THREAD

**Issue by crabvn** [davidroyer/vue2-editor#19]
I added one editor for summary and an other one for content. But while I type summary the editor for *content* also get that data.

http://imgur.com/a/06G71

**Comment by davidroyer** [comment]
Hello, Vue2Editor has been updated  to 2.0., which allows setting the **_id_** of each editor so that you can have multiple editors without issue. Also, an example of this has been added to the README.

I would really appreciate it if you could try it out and let me know if it works for you as needed. Thanks so much!



David

**Comment by crabvn** [comment]
![error](https://cloud.githubusercontent.com/assets/14814576/24987835/40ca1140-202c-11e7-8d3e-557aecb807cf.png)

It still returns error

**Comment by crabvn** [comment]
Hi David,

Sorry for respond late. I updated the issue on github.

Thanks

**Comment by davidroyer** [comment]
I am not sure what is happening with your situation.  Here is a working example I set up and attempted to make as similar to yours as possible (from what I could see).

[Gh-pages Example](https://davidroyer.github.io/vue2-editor/)
